## Old format redirects (for backward compatibility)
[[redirects]]
  from = "/sets/:setId"
  to = "/deeplink.html?setId=:setId"
  status = 301

[[redirects]]
  from = "/song/:songId"
  to = "/deeplink.html?songId=:songId"
  status = 301

[[redirects]]
  from = "/lyrics/:songNumberId"
  to = "/deeplink.html?songNumberId=:songNumberId"
  status = 301

## New format redirects with songbook ID and version ID (path-based)
[[redirects]]
  from = "/lyric/:songbookId/:versionId/:songNumber"
  to = "/lyrics.html?songbookId=:songbookId&versionId=:versionId&songNumber=:songNumber"
  status = 301

[[redirects]]
  from = "/music/:songbookId/:versionId/:songNumber"
  to = "/music.html?songbookId=:songbookId&versionId=:versionId&songNumber=:songNumber"
  status = 301

[[redirects]]
  from = "/set/:songbookId/:setNumber"
  to = "/sets.html?songbookId=:songbookId&setNumber=:setNumber"
  status = 301
